name: Laravel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  Twingate-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Install Twingate
      #   run: |
      #     echo "deb [trusted=yes] https://packages.twingate.com/apt/ /" | sudo tee /etc/apt/sources.list.d/twingate.list
      #     sudo apt update -yq
      #     sudo apt install -yq twingate

      - name: secret to file
        run: |
          echo $SECRET_KEY_BASE64 | base64 --decode > service_key.json
        env:
          SECRET_KEY_BASE64: ewogICJ2ZXJzaW9uIjogIjEiLAogICJuZXR3b3JrIjogInJleWx5ZXIudHdpbmdhdGUuY29tIiwKICAic2VydmljZV9hY2NvdW50X2lkIjogImExNGJmMmUwLTkxMDItNDJiNi05Njk0LTQwYjI3YzE0MTk0MiIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlHSEFnRUFNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQkcwd2F3SUJBUVFnSWowczNqYTBFWDc4REszQ1xuT1hzNkZYb29RNHZEeUl5N1dKTjhNVTlmb2thaFJBTkNBQVJ5eWh6b1psYzA3cFFFY2F1SXMyaWxwOGswNUF4RVxuVVg3U0ROcTFlS01OcS9weGJVelZTVzR4L1hWcHAzbjdVTDlaMWZnOHV1aWRaN0UvVkI2YmlmcjNcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0iLAogICJrZXlfaWQiOiAiWXAxRHJQVnVqeEFKZmJOMm93aFBKM0tXbkkxTlFNNG5EN0MyZEFwUVF2cyIsCiAgImV4cGlyZXNfYXQiOiAiMjAyNC0xMC0yMVQxOToxMToxOSswMDowMCIsCiAgImxvZ2luX3BhdGgiOiAiL2FwaS92NC9oZWFkbGVzcy9sb2dpbiIKfQ==

      - name: Install Twingate
        shell: bash
        run: |
          curl https://binaries.twingate.com/client/linux/install.sh | sudo bash
      
      - name: Setup and start Twingate
        shell: bash
        run: |
          sudo twingate setup --headless service_key.json
          sudo twingate start
          TWINGATE_STATUS=$(sudo twingate status)
          echo $TWINGATE_STATUS

      # - name: print secrets
      #   run: |
      #       echo $TWINGATE_SERVICE_KEY > service_key.json
      #       cat service_key.json
      #   shell: bash
      #   env:
      #     TWINGATE_SERVICE_KEY: ${{ secrets.SERVICE_KEY }}

      # - name: Setup and start Twingate
      #   run: |
      #     sudo twingate setup --headless service_key.json
      #     sudo twingate start

      - name: (optional) Twingate status
        run: twingate status

      - name: (optional) Twingate logs
        run: journalctl -u twingate  

      # - name: remove service_key secret
      #   run: |
      #     rm service_key.json
      #   shell: bash
      - name: (optional) Debug information for connection
        run: |
          nslookup sot.corp
          ping -c 4 sot.corp

      - name: Sync
        env:
          dest: "shariyl@10.10.10.10:/home/shariyl/servers/sot.corp/"
        run: |
          echo ${{secrets.DEPLOY_KEY}} > ~/deploy_key
          chmod 600 ~/deploy_key
          rsync -chav --delete \
            -e 'ssh -i ~/deploy_key -o StrictHostKeyChecking=no' \
            --exclude=.git --exclude=.env --exclude=vendor --exclude=storage --exclude=public --exclude=resources/views/home.blade.php ./ ${{env.dest}}

      - name: install packages
        uses: appleboy/ssh-action@master
        with:
          host: 10.10.10.10
          username: shariyl
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd /home/shariyl/servers/sot.corp
            composer install


      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          # HTTP Health Check for successful deployment testing
          # Check the following URLs one by one sequentially
          url: http://sot.corp
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 3s # Optional, only applicable to max-attempts > 1

      - run: echo "SUCCESS!!! 🤩 This job's status is ${{ job.status }}."

      - name: Stop Twingate
        run: sudo twingate stop
