name: Laravel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  Twingate-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: secret to file
        run: |
          echo $TWINGATE_SERVICE_KEY | base64 --decode > service_key.json
        env:
          TWINGATE_SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
          
      - name: Install Twingate
        shell: bash
        run: |
          curl https://binaries.twingate.com/client/linux/install.sh | sudo bash
      
      - name: Setup and start Twingate
        shell: bash
        run: |
          sudo twingate setup --headless service_key.json
          sudo twingate start
          TWINGATE_STATUS=$(sudo twingate status)
          echo $TWINGATE_STATUS

      - name: (optional) Twingate status
        run: twingate status

      - name: (optional) Twingate logs
        run: journalctl -u twingate  

      - name: remove service_key secret
        run: |
          rm service_key.json
        shell: bash
      
      - name: (optional) Debug information for connection
        run: |
          nslookup sot.corp
          ping -c 4 sot.corp

      - name: Sync
        env:
          dest: "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/servers/sot.corp/"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > ~/deploy_key
          chmod 600 ~/deploy_key
          rsync -chav --delete \
            -e 'ssh -i ~/deploy_key -o StrictHostKeyChecking=no' \
            --exclude=.git --exclude=.env --exclude=vendor --exclude=storage --exclude=public --exclude=resources/views/home.blade.php ./ ${{env.dest}}

      - name: install packages
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.SSH_USER }}/servers/sot.corp
            composer install


      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          # HTTP Health Check for successful deployment testing
          # Check the following URLs one by one sequentially
          url: http://sot.corp
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 3s # Optional, only applicable to max-attempts > 1

      - run: echo "SUCCESS!!! 🤩 This job's status is ${{ job.status }}."

      - name: Stop Twingate
        run: sudo twingate stop
